services:
  backend-api-1: &api
    image: docker.io/scaputo88/rinha-2025:1.1.7
    container_name: rinha_api-1
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - MAX_PARALLELISM=6
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - redis-socket:/var/run/redis
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256MB"

  backend-api-2:
    <<: *api
    container_name: rinha_api-2


  nginx:
    image: nginx:alpine
    container_name: rinha-nginx-java
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-api-1
      - backend-api-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256MB"

  redis:
    image: redis:7-alpine
    container_name: rinha-redis-java
    restart: unless-stopped
    command: [
      "redis-server",
      "--save", "''",
      "--appendonly", "no",
      "--maxclients", "5000",
      "--protected-mode", "no",
      "--hz", "10"
    ]
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256MB"


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
   redis-socket: