spring:
  datasource:
    url: jdbc:h2:file:./data/paymentsdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,threaddump
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles:
        all: 0.5,0.9,0.95,0.99
      minimum-expected-value:
        payments.processor.latency: 1ms
      maximum-expected-value:
        payments.processor.latency: 5s