spring:
  profiles:
    active: prod
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: never
  metrics:
    distribution:
      percentiles:
        all: 0.5,0.9,0.95,0.99
      minimum-expected-value:
        payments.processor.latency: 1ms
      maximum-expected-value:
        payments.processor.latency: 5s